disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- variable_name
- type_body_length
- file_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- R.generated.swift

line_length: 200